import = ["/Users/sidney/.config/alacritty/themes/themes/tomorrow_night.toml"]

[font]
size = 13

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Regular Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Command|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u000Ei"
key = "I"
mods = "Control"

[scrolling]
history = 2000

[window]
startup_mode = "Fullscreen"
title = "Alacritty"
