#!/bin/bash

if [ $# -eq 0 ]
then
	session_name="dev"
else
	session_name=$1
fi

if [[ ${#} -gt 1 ]]
then
	echo "dev [session_name]"
	exit 1
fi

tmux new -s ${session_name} -d
tmux send-keys -t ${session_name} "tmux source-file ~/.vim/tmux/dev.conf" C-m "clear" C-m
tmux attach -t ${session_name}
