local outline = require("symbols-outline")

outline.setup({
  highlight_hovered_item = false,
  auto_preview = false,
  -- width = 45,
  -- relative_width = false,
  show_numbers = true,
  winblend = 50,
  symbols = {
    File = { icon = "", hl = "@text.uri" },
    Module = { icon = "", hl = "@namespace" },
    Namespace = { icon = "", hl = "@namespace" },
    Package = { icon = "", hl = "@namespace" },
    Class = { icon = "", hl = "@type" },
    Method = { icon = "ƒ", hl = "@method" },
    Property = { icon = "", hl = "@method" },
    Field = { icon = "", hl = "@field" },
    Constructor = { icon = "", hl = "@constructor" },
    Enum = { icon = "", hl = "@type" },
    Interface = { icon = "", hl = "@type" },
    Function = { icon = "", hl = "@function" },
    Variable = { icon = "", hl = "@constant" },
    Constant = { icon = "", hl = "@constant" },
    String = { icon = "", hl = "@string" },
    Number = { icon = "#", hl = "@number" },
    Boolean = { icon = "", hl = "@boolean" },
    Array = { icon = "", hl = "@constant" },
    Object = { icon = "", hl = "@type" },
    Key = { icon = "", hl = "@type" },
    Null = { icon = "", hl = "@type" },
    EnumMember = { icon = "", hl = "@field" },
    Struct = { icon = "", hl = "@type" },
    Event = { icon = "", hl = "@type" },
    Operator = { icon = "", hl = "@operator" },
    TypeParameter = { icon = "", hl = "@parameter" },
    Component = { icon = "", hl = "@function" },
    Fragment = { icon = "", hl = "@constant" },
  }
  -- symbols = {
  --   File = { hl = "@text.uri" },
  --   Module = { hl = "@namespace" },
  --   Namespace = { hl = "@namespace" },
  --   Package = { hl = "@namespace" },
  --   Class = { hl = "@type" },
  --   Method = { hl = "@method" },
  --   Property = { hl = "@method" },
  --   Field = { hl = "@field" },
  --   Constructor = { hl = "@constructor" },
  --   Enum = { hl = "@type" },
  --   Interface = { hl = "@type" },
  --   Function = { hl = "@function" },
  --   Variable = { hl = "@constant" },
  --   Constant = { hl = "@constant" },
  --   String = { hl = "@string" },
  --   Number = { hl = "@number" },
  --   Boolean = { hl = "@boolean" },
  --   Array = { hl = "@constant" },
  --   Object = { hl = "@type" },
  --   Key = { hl = "@type" },
  --   Null = { hl = "@type" },
  --   EnumMember = { hl = "@field" },
  --   Struct = { hl = "@type" },
  --   Event = { hl = "@type" },
  --   Operator = { hl = "@operator" },
  --   TypeParameter = { hl = "@parameter" },
  -- },
})

nnoremap("<C-\\>", outline.toggle_outline)
