send-keys "source .venv/bin/activate" C-m
send-keys "nvim" C-m

split-window -v -l 20%
select-pane -t 2
send-keys "source .venv/bin/activate" C-m

split-window -h -l 50%
select-pane -t 3
send-keys "source .venv/bin/activate; claude" C-m

new-window -n Shell
select-window -t 2
send-keys "source .venv/bin/activate" C-m
send-keys "btop" C-m
split-window -v -l 50%
select-pane -t 2
send-keys "source .venv/bin/activate" C-m

# Back to the first window
select-window -t 1
select-pane -t 1
